---

- hosts: all ## /etc/ansible/hosts  file 
  become: true ## sudo users 
  vars:   ## create global variable

  ## Local machine  variable

    local_Copy_stc1: /home/nikto/Music/server-script.sh   # Enter your script full path
    local_fetch_dest_path: /tmp/output-file/    # Enter your destination file path store all outputs
     
  ## Remote machine variable


    remote_dest1: /tmp      # Enter remote server file path
    remote_path: /tmp/server-script.sh  # Run script path  
    remote_username: root      # Enter remote server username
    remote_file_permission: 775 # Enter file permission ex:- chmod 775 <file-name>
    remote_Fetch_stc1: /tmp/script-output.txt      # on remote server which file copy  enter full path
    remote_server_run_command: sh /tmp/server-script.sh > /tmp/script-output.txt  # Enter your command which commands run in remote server
    remove_text_file: rm /tmp/script-output.txt      # Enter ouptut file name
    remove_server_script: rm /tmp/server-script.sh   # Enter server script name 

  tasks:

  - name: "copy script"
    copy:                   # copy command for local to remote server
      src: "{{local_Copy_stc1}}"
      dest: "{{remote_dest1}}"

  - name: "script permission"
    file:
      path: "{{remote_path}}"
      owner: "{{remote_username}}"
      group: "{{remote_username}}"
      mode: "{{remote_file_permission}}"

  - name: "shell run"
    ansible.builtin.shell: '{{remote_server_run_command}}'

## copy any file remote server to local machine using fetch command ---------------------------------------

  - name: "remote to local file send"
    run_once: yes
    ansible.builtin.fetch:
      src: "{{remote_Fetch_stc1}}"   ## enter full file path remote server 
    #  dest: output-file/             ## auto.. create one folder name is output-file on this file path
      dest: "{{local_fetch_dest_path}}"
      flat: yes                      ## flat 

## Ends fetch command script ---------------------------------------------------------------

  - name: "Delete script remote server"
    ansible.builtin.shell: "{{remove_server_script}}"

  - name: "Delete ouput text file on remote server"
    ansible.builtin.command: "{{remove_text_file}}"
