---

- name: server 1 {{ s1_user }} Add SSH Public key
  become: true
  authorized_key:
    user: "{{ s1_user }}"
    state: present
    key: "{{ ssh_pulic_key }}"
  ignore_errors: true


- name: server 2 {{ s2_user }} Add SSH Public Key 
  become: true
  become_user: "{{ s2_user }}"
  authorized_key:
    user: "{{ s2_user }}"
    state: present
    key: "{{ ssh_pulic_key }}"
  ignore_errors: true


- name: server 3 {{ s3_user }} Add SSH Public Key 
  become: true
  become_user: "{{ s3_user }}"
  authorized_key:
    user: "{{ s3_user }}"
    state: present
    key: "{{ ssh_pulic_key }}"
  ignore_errors: true


